# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - https://api.misiki.io/graphql
        # headers:
        #   Authorization: 'Bearer ${TOKEN}'
      - ./$houdini/graphql/schema.graphql
    documents:
      - '**/*.gql'
      - ./$houdini/graphql/documents.gql
   